REMOVE_DEAD_ENTITIES_EVERY = 3.5 # seconds
GAME_MAX_LEVEL = 10
INCREASE_LEVEL_EVERY = 60. # seconds
TRAIL_MAX_LENGTH = 50 # positions

# player
PLAYER_SIZE = 12.
PLAYER_DEFAULT_SPEED_RANGE = (100., 1000.) # min, max: depends on the distance to the gravity point
PLAYER_DEFAULT_MAX_HEALTH = 100.
PLAYER_DEFAULT_REGEN_RATE = 1.5 # hp per second
PLAYER_DEFAULT_MAX_ENERGY = 1000
PLAYER_ENERGY_DECAY_RATE = 10. # energy per second
PLAYER_STARTING_ENERGY = PLAYER_DEFAULT_MAX_ENERGY // 2

PLAYER_SHOT_COST = 150

PLAYER_STARTING_POSITION = 500., 500.

# projectile
PROJECTILE_DEFAULT_SIZE = 6.
PROJECTILE_DEFAULT_SPEED = 250. # pixels per second
PROJECTILE_DEFAULT_LIFETIME = 8. # seconds
PROJECTILE_DEFAULT_DAMAGE = 25.

# energy orb
ENERGY_ORB_SIZE = 8.
ENERGY_ORB_DEFAULT_LIFETIME = 5. # seconds
ENERGY_ORB_DEFAULT_ENERGY = 100.
ENERGY_ORB_COOLDOWN_RANGE = (0.5, 3.5)
