REMOVE_DEAD_ENTITIES_EVERY = 240 # ticks
TRAIL_MAX_LENGTH = 50

# player
PLAYER_SIZE = 30
PLAYER_MAX_HEALTH = 100.
PLAYER_MAX_ENERGY = 1000
PLAYER_STARTING_ENERGY = PLAYER_MAX_ENERGY // 10

# projectile
PROJECTILE_DEFAULT_SIZE = 8
